name: ytcc
version: git
summary: ytcc - The channel checker
description: |
  Command Line tool to keep track of your videos channels (principly youtube)
  without signing up your account.

grade: devel
confinement: devmode

parts:
  ytcc:
    source: .
    plugin: python
    python-version: python3
    stage-packages: [mpv]

apps:
  ytcc:
    command: bin/ytcc
